

<main>
    <header class="jumbotron main-header">
        <h1 class="display-4"><?= $title?></h1>
        <p class="lead display-6">Les derniers articles</p>
    </header>

    <div class="container-fluid">
        <div class="row  ">
            <?php foreach($posts as $dataPosts): ?>
                <div class="col-md-4 mb-5">
                    <div class="card border-warning h-100">

                        <div class="card-header p-4">
                            <h3><?= $dataPosts['title']?></h3>
                            <p><?= $dataPosts['categoryName']?> </p>
                        </div>

                        <div class="card-body p-4 ">
                            <p class="card-text"><?=$dataPosts['content'];?> [..]</p>
                            <a class="more" href="post_details.php?idPost=<?=$dataPosts['id'];?>"> En lire Plus</a>
                        </div>

                        <div class="card-footer  pt-3 border">
                            <p> <?= $dataPosts['firstname'] ." " .$dataPosts['lastname']?></p>
                            <p> <?= $dataPosts['created_date']?></p>
                        </div>

                    </div>
                </div>
            <?php endforeach; ?>

        </div>
    </div>
</main>
