<div class="container-fluid">
    <main>
        <header>
            <h1> <?= htmlspecialchars($posts['title'])?> </h1>
            <p>Dans la catégorie  <?= htmlspecialchars($posts['name']) ?></p>
            <p>   Rédigé par <?= htmlspecialchars($posts['firstname']) ." ".htmlspecialchars($posts['lastname']) ?>  le  <?=htmlspecialchars($posts['created_date']) ?></p>
        </header>
        <div class="container-fluid">
            <section>
                <article class="article mb-4">
                    <div class="row ">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <?=htmlspecialchars($posts['content']);?>
                        </div>
                        <div class="col-md-4 mb-2"></div>
                    </div>
                </article>
            </section>

            <section>
                <article class="list_comments">
                    <div class="row ">
                        <div class="col-md-8 mt-5 mb-5 pt-5">
                            <h3>Liste des commentaires
                                <?php if (count($comments) > 0) : ?>
                                    <small>(<?= count($comments); ?>)</small>
                                <?php endif; ?>
                            </h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="list_comments_div col-md-3 rounded">
                            <?php if (!empty($comments)) : ?>
                                <ul class="list-group text-white">
                                    <?php foreach ($comments as $comment) : ?>
                                        <li class="list-group-item bg-primary text-white  mt-3">
                                            <i class="fa fa-comment" aria-hidden="true"></i>
                                            Rédigé par
                                            <strong><?= htmlspecialchars($comment['nickname']) ?></strong>
                                            <div class="py-2"><?= htmlspecialchars($comment['content']) ?></div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else : ?>
                                <p>Cet article n'a pas encore de commentaire</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </article>
            </section>
        </div>

        <div class="row">
            <div class="col-md-4 mt-5 mb-5 pt-5">
                <section>
                    <article>

                        <form action="<?= $_SERVER['REQUEST_URI'] ?>" method="post" class="form">
                            <!---Action : permet de garder l URl avc le get et ca evite de creer un nouveau fichier  on aurait pu mettre l url en dur aussi -->

                            <input type="hidden"  name="postId" value="<?= $posts['id'] ?>"
                            <fieldset>
                                <legend> <h3 >Ajouter un commentaire</h3> </legend>
                                <div class="form-group">
                                    <label  class="m-2"  for="nickname">Pseudo  </label>
                                    <input class="form-control m-2" id="nickname" name="nickname" type="text"  value=" <?= $commentNickname?? "" ?>">
                                    <?= $commentPosts->getInvalidFeedback('pseudoError')?>

                                </div>
                                <div class="form-group">
                                    <label class="m-2" for="content"> Commentaire </label>
                                    <textarea class="form-control m-2"  name="content">  value=" <?= $commentContent?? "" ?>"</textarea>
                                    <?= $commentPosts->getInvalidFeedback('contentError')?>
                                </div>
                                <button type="submit"  class="btn  btn-lg btn-success m-2" name="addComment"  >Ajouter</button>
                                <button type="submit"  href="post_details.php" class="btn btn-lg btn-warning m-2" >Annuler</button>
                            </fieldset>
                            </input>

                        </form>
                    </article>
                </section>
            </div>
            <div class="col-md-8"></div>
        </div>
    </main>
</div>