
<main>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">

            <li class="breadcrumb-item">Administration</li>
            <li class="breadcrumb-item">Login</li>
        </ol>
    </nav>
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card   border-warning text-black" style="border-radius: 1rem;">

                        <form action="login.php" method="post" class="card-body p-5 text-center">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                <p class="text-black-50 mb-5">Please enter your login and password!</p>

                                <div class="form-outline form-white mb-4">
                                    <label class="form-label" for="typeEmailX">Email</label>
                                    <input type="email" id="typeEmailX" name="email" class="form-control form-control-lg" />
                                    <small> <?php if(isset($errors['email'])) echo $errors['email']; ?></small>
                                </div>

                                <div class="form-outline form-white mb-4">
                                    <label class="form-label" for="typePasswordX">Password</label>
                                    <input type="password" id="typePasswordX" name="password" class="form-control form-control-lg" />

                                </div>

                                <p class="small mb-5 pb-lg-2"><a class="text-black-50" href="#!">Forgot password?</a></p>

                                <button class="btn btn-outline-light bg-primary btn-lg px-5" type="submit" name="login">Login</button>
                            </div>

                            <div>
                                <p class="mb-0">Don't have an account? <a href="#!" class="text-black-50 fw-bold">Sign Up</a></p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>